name: POEM
channels:
  - conda-forge
dependencies:
  - python=3.9
  - black==22.3.0
  - numpy==1.22.2
  - matplotlib==3.5.1
  - pytorch==1.9.1
# - pytorch-cuda==11.3 # Replace pytorch==1.9.1 with cuda version for gpu use.
  - torchvision==0.10.0 # Pinned due to torchmeta (see below)
  - gym==0.21.0
  - pip
  - pip:
    - array2gif==1.0.4
    - torch-ac==1.1.0
    - torchmeta==1.8.0
    - gputil==1.4.0
    - wandb==0.12.18
# Note: Torchmeta limits torch versions (to torchvision<0.11.0 and >=0.5.0, as in e.g. [this issue](https://github.com/tristandeleu/pytorch-meta/issues/161)
# If not running FSL experiments, torchmeta is not required and package versions are more flexible.